### ISSUE TITLE
Can Not save values

### ISSUE THREAD

**Issue by jay7210** [codecae/betaflight-tx-lua-revised#9] opened 2017-09-14 18:54 UTC
Can not save new values. Goes through the actions, Takes a while on save page then refreshes with the original values.

Running BFF3, crossfire X9D.

**Comment by codecae** [comment] 2017-09-14 18:58
What are your gyro and pid rates?  Are you using dynamic filtering?

**Comment by si618** [comment] 2017-09-15 00:48
I'm hitting the same issue, as is another guy in our local club.  We're both using dynamic filtering. I'm on ßFF3, X9D with Crossfire micro rx v2 (2.06). PIDs and rates as follows:

> set setpoint_relax_ratio = 20
> set dterm_setpoint_weight = 180
> set p_pitch = 56
> set d_pitch = 43
> set p_roll = 38
> set d_roll = 38
> set p_yaw = 68
> set rc_rate = 88
> set rc_rate_yaw = 88
> set roll_srate = 68
> set pitch_srate = 68
> set yaw_srate = 68

Also getting a lua script error saving vtx changes via tramp telemetry, but I'll raise another issue with more details.

**Comment by codecae** [comment] 2017-09-15 02:41
Pids and rates are kind of irrelevant, unfortunately.  I think the core issue is that a ton of cpu is being used up by dynamic filtering and this is causing things to time out.  I would suggest using lower loop speeds to see if it yields better result.  Maybe try 4k/4k to see if the saves will work.

**Comment by si618** [comment] 2017-09-15 02:45
Thanks. Think I'm running 8k/4k but will drop it down further and see what happens, cheers!

**Comment by codecae** [comment] 2017-09-15 02:58
Also -- I have updated the scripts today, so maybe try reinstalling the newest commit on the crsf branch to see if it plays nicer.

**Comment by si618** [comment] 2017-09-15 09:15
Your intuition is correct, just tested and CPU <=15% is the max on my FC before saving fails to stick. Under that it saves.

**Comment by codecae** [comment] 2017-09-15 11:55
Try raising the loop speeds back to 8k and disable dynamic filtering... I bet the saves will work in this config as well.

**Comment by si618** [comment] 2017-09-15 12:15
I did try feature -dynamic_filtering, which lowered cpu ~10%, but it was not enough, had to lower loops times as well. 

It's a little odd as I can run the stock ßF lua scripts with frsky rx on the same tramp vtx and ßFF3 with dynamic filtering enabled and cpu ~55%, and that saves fine?

**Comment by codecae** [comment] 2017-09-15 12:51
Internally, the CRSF and FrSky protocols handle timing differently in the flight controller.  CRSF seems to be a bit more strict about how packets are timed, down to the 10's of microseconds.   I have a few other suspicions why this is happening so I'll try a few more things in the betaflight code to see if I can find a way around it.  Just a suspicion, at this point, but I think I may have a way to address this issue.

**Comment by TempleClause** [comment] 2017-09-18 15:21
Same here, saving does not work with 8khz and dynamic filtering... works fine with 4khz and no dynamic filtering... I'm still on a F3 board, I hope this works better with an F4 board which I will soon install.

Thanks for the awesome work anyways!

**Comment by codecae** [comment] 2017-09-18 15:24
Dynamic Filtering is very CPU intensive, especially on F3 boards at higher loop speeds.  It's not surprising that there is contention.  It should run fine on 8k/8k on a F4 board.

**Comment by codecae** [comment] 2017-09-18 15:25
All things considered, you should feel very little difference at 4k/4k, if any at all.

**Comment by TempleClause** [comment] 2017-09-18 15:34
Okay, I will have an F4 board soon and will report back how it goes!

**Comment by PrestonHack** [comment] 2017-09-19 03:08
I have tested this we were aware of this in the development. The gyro/pid timing and dynamic filtering effect the ability to save. For the reasons codecae has explained. 
The current recommendation is this:

If you are doing a tuning flight TURN OFF DYNAMIC FILTER this makes sense to do anyway because you don't want to tune with filtering on however you can and it works fine.

Running higher pid rates reduces the effectiveness of saves 8k should work fine it did on F4 & F3 in tests.

Personally I use 4k/4k dynamic ON with a F4 and it works fine. I have experienced issues where if you care close to the aircraft you antenna orientation matters even more so try rotating your controller and saving.

**Comment by codecae** [comment] 2017-09-19 03:32
Just so everyone knows, this is something that I will continue to track down and improve.

**Comment by si618** [comment] 2017-09-20 00:46
@codecae I've been stalking your slack chat with mikeller ;-) so will test latest ßF build and 1.0-rc2 of lua scripts when I get home from work tonight. 

Also, Crossfire 2.07 is out, so will test against 2.06 and then upgrade to 2.07 and test again. Thanks for your efforts!

**Comment by PrestonHack** [comment] 2017-09-20 00:54
only use stable releases uncheck show unstable releases this is only confirmed working in crossfire fw 2.06

**Comment by si618** [comment] 2017-09-20 02:55
Ack. I should [RTFM](https://github.com/codecae/betaflight-tx-lua-revised#installing) more thoroughly.

**Comment by codecae** [comment] 2017-09-20 14:09
Have some good news.  Nothing is committed yet, but I have a fix for this issue.  I have been successfully able to save using 8k/8k with dynamic filters enabled on a F3 without any issue.  If this change goes in, it should also improve the overall performance tremendously.  Again, this is still pending review, but one way or another we will address this problem.

**Comment by codecae** [comment] 2017-09-20 14:13
@si618 hah.. lurking the betaflightgroup slack, are we?

**Comment by si618** [comment] 2017-09-20 14:32
:) looks like you'll have it sorted out shortly. 

I could only get 4k/4k saving (~17% CPU) with latest ßF build and rc2 of the lua scripts, but I can see your PR and Martin's, so will try again once they're merged.

Tested another quad hooked up to smartport, and rc2 scripts worked a treat, cheers!

**Comment by codecae** [comment] 2017-09-22 03:49
I create a PR to correct this issue.  Will inform the thread if/when the merge happens.

**Comment by codecae** [comment] 2017-09-23 19:43
Hang in there.. working through the final stages of agreement for the merge.  Shouldn't be much longer.

I have tested the firmware deeply on F3 and F4's on both CRSF and S.Port.  You will be pleasantly surprised with the outcome of this change.

**Comment by codecae** [comment] 2017-10-05 19:06
I have posted an archive that contains all targets that should enable saves until Betaflight merges the change into the mainline code.

*PLEASE KEEP IN MIND THAT THIS FIRMWARE IS A ONE-OFF INTERIM UPDATE THAT IS NOT YET PART OF THE SUPPORTED BETAFLIGHT CODEBASE.  IF YOU HAVE ISSUES, PLEASE RETURN HERE TO RAISE THEM OR OPEN THEM IN MY FORK OF THE BETAFLIGHT REPO AND NOT THE BETAFLIGHT REPO!*

[Click here to download the ZIP of all targets](http://bit.ly/2xYtGnE)

**Comment by codecae** [comment] 2017-10-09 22:16
This issue has been corrected and is now available in the master branch of Betaflight build 242 and greater.  It will be released in stable release 3.2.1 but can be downloaded now from the build repository.

[Click here to visit the available builds for Betaflight](https://ci.betaflight.tech/view/all/builds)

**Closed by codecae** 2017-10-09 22:16 UTC
Labels: help wanted
