### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by umbertoghio** [codecae/betaflight-tx-lua-revised#7] opened 2017-09-12 21:34 UTC
OK, bothering you here instead of FB, here my setup and what I tried so far:
Taranis X9D SE with Crossfire Micro TX running OpenTX 2.2
Crossfire nano RX with Betaflight F3 FC on UART1, CRSF protocol and running 3.2 RC5
Started with a clean SD and installed sdcard-taranis-x9-2.2V0010.zip
Merged the Scripts content to my SD Scripts folder from the CRSF Branch
I run the Lua in the Telemetry folder, I see the usual Crossfire Lua page showing both TX and RX, but then get an "Unknown error" when selecting either.
I suspect I need to enable something in Betaflight, but I followed the related issues up to 4120 without understanding if some requirement is not met.
I used to run the FrSky Lua scripts OK from the Smartport telemetry line on the X4R
Any clues? going to deep dive in the LUA code to find more

**Comment by umbertoghio** [comment] 2017-09-12 21:36
Ok, some updates :-)
I switched to the SRC code instead of SDCARD code and put debug=true, now I am getting two extra lines in the list, Betaflight and Betaflight 3.2.0:BFF3 and it works!
Now removed debug and it still shows Betaflight and Betaflight 3.2.0:BFF3, all works except VTX page. Trying to switch again now to SDCARD instead of SRC

**Comment by codecae** [comment] 2017-09-12 21:39
debug is not necessary.  that was only for early preliminary testing.

You may be experiencing an issue in the minified code.  try using the src contents for now and I'll look into the minified code issue

**Comment by umbertoghio** [comment] 2017-09-12 21:41
OK, final update, seems that it was my fault all along :-) tried the minified code again and it works, so somehow here was my issue:
- I was using RC4 instead of the required RC5 (recommend to add that to the readme page in BOLD RED :-)
- Somehow after upgrading the "crossfire device" was not appearing right away
- After some messing up on my side, without knowing what exactly I did, now it work consistently.
Amazing work, thank you so much!

**Comment by codecae** [comment] 2017-09-12 21:44
I'll update the readme files

**Comment by umbertoghio** [comment] 2017-09-12 21:49
OK, something else to report:
I get a GV Use: xxxxxx number moving in the bottom right corner (ok, it appear after running a "reload" of the page )
The VTX page does not shows data (all the rest seems OK)
I am using a TBS Unify Pro V2 connected with SmartAudio on UART3 TX on the FC
SA on OSD works OK 
Any help on how to troubleshoot that?

**Comment by codecae** [comment] 2017-09-12 22:07
I'll take a look. I think the GV Use thing is a transmitter setting.  I'll look and confirm.

**Comment by umbertoghio** [comment] 2017-09-12 22:14
OK, the GV box appear when doing a refresh and goes away after doing another refresh
PS: the script pages are great, love what you achieved!

**Comment by codecae** [comment] 2017-09-12 22:28
I'm asking OpenTx about the GV Use box.  With respect to smart audio -- it works fine for me.  Is your battery plugged in?  The vtx needs power for the smartaudio to work.

**Comment by umbertoghio** [comment] 2017-09-13 09:04
About Smartaudio, 
It works on the OSD, I confirm it is powered up as I do my test with the battery connected.
When going on the VTX page all the values shows as --
When pressing enter on a value to change it I get a
Script syntax error
?:0
attempt to perform arithmetic on field 'val
If I enable debug will I get something in the log file? Or is there another way to debug further?

**Comment by codecae** [comment] 2017-09-13 11:56
Debug will not help.  Replace /SCRIPTS/BF/X9/vtx.lua with the sec version and see if if it can provide a line number where the error occurs.

**Comment by umbertoghio** [comment] 2017-09-13 15:30
Hi, see the video of the attempt with source file here: https://youtu.be/hE4Dxs3pQ3Q the error occurs understandably when trying to change a value that is not loaded, the mystery is why the value are not red in the first place :-)

**Comment by codecae** [comment] 2017-09-13 19:48
The work fine on mine :/  I can't reproduce this issue.

**Comment by codecae** [comment] 2017-09-13 19:51
I'll see if I can reproduce on my betaflight f3.

**Comment by umbertoghio** [comment] 2017-09-14 13:04
OK, a little update, some progress: 
I have update drone N2 to RC5 and instead of restoring settings as I usually do I set up everything in Betaflight manually from scratch, then copied the settings (diff command) to drone N1, they are identical and currently behave in the same way.

Now the VTX (kind of) works!
I can get the actual values my VTX is currently set (freq, power, etc), I can change a value on the screen
![img_2515](https://user-images.githubusercontent.com/25666241/30431051-9ccdfed4-995d-11e7-9182-d13bf3dee597.JPG)

 but when I save I get the error:

![img_2516](https://user-images.githubusercontent.com/25666241/30431045-977479ae-995d-11e7-92d6-021e041d3820.JPG)

I am currently using the SRC version (not the minified) and at line 50 of the Lua script I have:

if self.values[2] > 0 and self.values[3] > 0 then

Same error whatever field I change (band, power, channel)

getting further :-)

**Comment by codecae** [comment] 2017-09-14 13:31
I made an update to the repository to correct the issues in the vtx template.

Please try using the latest commit in the crsf branch.

**Comment by umbertoghio** [comment] 2017-09-14 18:40
Man, it works perfectly!
thank you very much for all the effort and support :-)

**Comment by codecae** [comment] 2017-09-14 18:40
no problem :)  glad I can help.  Mind if I close this issue?

**Comment by umbertoghio** [comment] 2017-09-14 19:38
Absolutely! 
Again thanks !

**Closed** 2017-09-14 19:42 UTC
